### PR TITLE
fix: radio button selectability and static duties and responsibilitie…

### LINKED ISSUE #93: Ballot Form: Clicks On Candidate Photo Does Not Select The Associated Radio Button
Associated radio button for a candidate photo doesn't get selected upon clicking the photo. See the video below

https://github.com/BSIT-3-1-APPDEV/PUPSRC-AutomatedElectionSystem/assets/162773681/896d29dd-8d67-4a9f-9e42-83e8c43e2dae

### LINKED ISSUE #96: Ballot Form: Static Duties and Responsibilities
The ballot form duties and responsibilities show a modal containing the information of a particular position. As per my last check, the modal information is static and hardcoded HTML. Make sure that you are fetching from the description column of position table. 

**Modal:**
image

**HTML:**
image

### PR DESCRIPTION
**Pull request by Andrea-Villalobos**
…s to close Ballot Form: Clicks On Candidate Photo Does Not Select The Associated Radio Button #93, close Ballot Form: Static Duties and Responsibilities #96

- added label for the candidate image
- dynamic duties and responsibilities

Note: 
Here is a sample sql. I modified the candidate table where program, year_level, and section columns are added. 
Sample description of position data for duties and responsibilities.
[sampledb.txt.txt](https://github.com/BSIT-3-1-APPDEV/PUPSRC-AutomatedElectionSystem/files/15310916/sampledb.txt.txt)

### CODE REVIEW

File: src/ballot-forms.php [hunk 1]
```diff
@@ -65,7 +65,30 @@
...
+          $personality = "JPIANs";   
+      } else if ($org_acronym == 'piie'){
+          $personality = "IEhinyero";  
+      } else if ($org_acronym == 'jmap'){
+          $personality = "Marketista"; 
+      } else if ($org_acronym == 'sco'){
+          $personality = "Iskolar"; 
+      }
+?>
+
```
Comment (Carl-Tabuso) [inline src/ballot-forms.php:91]: You can move this to the organization-list.php file. Let's strive for a cleaner and modular code.

**Review by Carl-Tabuso — APPROVED** [review]
Linked issues have been addressed. Check comments for suggestion for improvements.
